In [1]:
!pip uninstall -y transformers peft accelerate
!pip install transformers==4.38.2
!pip install accelerate==0.27.2
!pip install peft==0.8.2
!pip install sentencepiece datasets evaluate -q

Found existing installation: transformers 5.0.0
Uninstalling transformers-5.0.0:
  Successfully uninstalled transformers-5.0.0
Found existing installation: peft 0.19.1
Uninstalling peft-0.19.1:
  Successfully uninstalled peft-0.19.1
Found existing installation: accelerate 1.13.0
Uninstalling accelerate-1.13.0:
  Successfully uninstalled accelerate-1.13.0
Collecting transformers==4.38.2
  Downloading transformers-4.38.2-py3-none-any.whl.metadata (130 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.7/130.7 kB 10.3 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.38.2) (3.29.0)
Collecting huggingface-hub<1.0,>=0.19.3 (from transformers==4.38.2)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.38.2) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.38.2) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.38.2) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.38.2) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.38.2) (2.32.4)
Collecting tokenizers<0.19,>=0.14 (from transformers==4.38.2)
  Downloading tokenizers-0.15.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.38.2) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.38.2) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.38.2) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.38.2) (1.4.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.38.2) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.38.2) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.38.2) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.38.2) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.38.2) (2026.4.22)
Downloading transformers-4.38.2-py3-none-any.whl (8.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.5/8.5 MB 96.5 MB/s eta 0:00:00
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 32.1 MB/s eta 0:00:00
Downloading tokenizers-0.15.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 108.0 MB/s eta 0:00:00
Installing collected packages: huggingface-hub, tokenizers, transformers
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 1.11.0
    Uninstalling huggingface_hub-1.11.0:
      Successfully uninstalled huggingface_hub-1.11.0
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.22.2
    Uninstalling tokenizers-0.22.2:
      Successfully uninstalled tokenizers-0.22.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sentence-transformers 5.4.1 requires transformers<6.0.0,>=4.41.0, but you have transformers 4.38.2 which is incompatible.
Successfully installed huggingface-hub-0.36.2 tokenizers-0.15.2 transformers-4.38.2
Collecting accelerate==0.27.2
  Downloading accelerate-0.27.2-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate==0.27.2) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate==0.27.2) (26.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate==0.27.2) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate==0.27.2) (6.0.3)
Requirement already satisfied: torch>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from accelerate==0.27.2) (2.10.0+cu128)
Requirement already satisfied: huggingface-hub in /usr/local/lib/python3.12/dist-packages (from accelerate==0.27.2) (0.36.2)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.12/dist-packages (from accelerate==0.27.2) (0.7.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.10.0->accelerate==0.27.2) (1.5.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->accelerate==0.27.2) (1.4.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->accelerate==0.27.2) (2.32.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->accelerate==0.27.2) (4.67.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.10.0->accelerate==0.27.2) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.10.0->accelerate==0.27.2) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub->accelerate==0.27.2) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub->accelerate==0.27.2) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub->accelerate==0.27.2) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub->accelerate==0.27.2) (2026.4.22)
Downloading accelerate-0.27.2-py3-none-any.whl (279 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 280.0/280.0 kB 18.5 MB/s eta 0:00:00
Installing collected packages: accelerate
Successfully installed accelerate-0.27.2
Collecting peft==0.8.2
  Downloading peft-0.8.2-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from peft==0.8.2) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from peft==0.8.2) (26.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft==0.8.2) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from peft==0.8.2) (6.0.3)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from peft==0.8.2) (2.10.0+cu128)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (from peft==0.8.2) (4.38.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from peft==0.8.2) (4.67.3)
Requirement already satisfied: accelerate>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from peft==0.8.2) (0.27.2)
Requirement already satisfied: safetensors in /usr/local/lib/python3.12/dist-packages (from peft==0.8.2) (0.7.0)
Requirement already satisfied: huggingface-hub>=0.17.0 in /usr/local/lib/python3.12/dist-packages (from peft==0.8.2) (0.36.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.17.0->peft==0.8.2) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.17.0->peft==0.8.2) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.17.0->peft==0.8.2) (1.4.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.17.0->peft==0.8.2) (2.32.4)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.17.0->peft==0.8.2) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.8.2) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.8.2) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.8.2) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.8.2) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.8.2) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.8.2) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.8.2) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.8.2) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.8.2) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.8.2) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.8.2) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.8.2) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.8.2) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.8.2) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.8.2) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.8.2) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.8.2) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.8.2) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.8.2) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.8.2) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.8.2) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.13.0->peft==0.8.2) (1.5.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers->peft==0.8.2) (2025.11.3)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /usr/local/lib/python3.12/dist-packages (from transformers->peft==0.8.2) (0.15.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.13.0->peft==0.8.2) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.13.0->peft==0.8.2) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.17.0->peft==0.8.2) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.17.0->peft==0.8.2) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.17.0->peft==0.8.2) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.17.0->peft==0.8.2) (2026.4.22)
Downloading peft-0.8.2-py3-none-any.whl (183 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.4/183.4 kB 17.5 MB/s eta 0:00:00
Installing collected packages: peft
Successfully installed peft-0.8.2
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 7.9 MB/s eta 0:00:00

In [70]:
# =========================================================
# IMPORT
# =========================================================

import pandas as pd
import torch
import shutil
import re

from sklearn.model_selection import train_test_split

from datasets import Dataset

from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments
)

In [27]:
# =========================================================
# HAPUS CHECKPOINT LAMA
# =========================================================

shutil.rmtree("./indobart-qg", ignore_errors=True)

In [31]:
# =========================================================
# LOAD DATASET
# =========================================================

df = pd.read_csv("H5_dataset_ML.csv")

In [32]:
# =========================================================
# BERSIHKAN DATA
# =========================================================

df["input"] = df["input"].astype(str).str.strip()
df["target"] = df["target"].astype(str).str.strip()

df = df[
    (df["input"] != "") &
    (df["target"] != "")
]

df = df.drop_duplicates()

df = df.reset_index(drop=True)

In [33]:
## =========================================================
# INFO
# =========================================================

print("=" * 50)
print("JUMLAH DATA")
print("=" * 50)

print(len(df))

print("\nCONTOH:")
print(df.head())

==================================================
JUMLAH DATA
==================================================
4674

CONTOH:
                                               input  \
0   generate siapa: Pagi itu Rina bangun lebih awal.
1   generate kapan: Pagi itu Rina bangun lebih awal.
2  generate siapa: Rina merapikan tempat tidur di...
3  generate apa: Rina merapikan tempat tidur di k...
4  generate dimana: Rina merapikan tempat tidur d...

                                            target
0           Siapa yang bangun pagi itu lebih awal?
1                              Kapan Rina bangun ?
2  Siapa yang merapikan tempat tidur di kamar nya?
3              Apa yang Rina rapikan di kamar nya?
4             Di mana Rina merapikan tempat tidur?

In [34]:
# =========================================================
# SPLIT DATASET
# =========================================================

train_df, temp_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42
)

valid_df, test_df = train_test_split(
    temp_df,
    test_size=0.5,
    random_state=42
)

In [64]:
test_df.to_csv(
    "H6_test_dataset.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Test dataset berhasil disimpan")

Test dataset berhasil disimpan

In [35]:
# =========================================================
# CONVERT DATASET
# =========================================================

train_dataset = Dataset.from_pandas(train_df)
valid_dataset = Dataset.from_pandas(valid_df)
test_dataset = Dataset.from_pandas(test_df)

In [40]:
# =========================================================
# LOAD MODEL
# =========================================================

model_name = "facebook/bart-base"

tokenizer = AutoTokenizer.from_pretrained(
    model_name
)

model = AutoModelForSeq2SeqLM.from_pretrained(
    model_name
)

config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/558M [00:00<?, ?B/s]

In [42]:
# =========================================================
# TOKENISASI
# =========================================================

max_input_length = 128
max_target_length = 64


def preprocess_function(examples):

    inputs = examples["input"]

    targets = examples["target"]

    model_inputs = tokenizer(
        inputs,
        max_length=max_input_length,
        truncation=True,
        padding="max_length"
    )

    labels = tokenizer(
        text_target=targets,
        max_length=max_target_length,
        truncation=True,
        padding="max_length"
    )

    # ubah padding jadi -100
    labels["input_ids"] = [

        [
            token if token != tokenizer.pad_token_id else -100
            for token in label
        ]

        for label in labels["input_ids"]
    ]

    model_inputs["labels"] = labels["input_ids"]

    return model_inputs

In [43]:
# =========================================================
# TOKENIZE
# =========================================================

tokenized_train = train_dataset.map(
    preprocess_function,
    batched=True
)

tokenized_valid = valid_dataset.map(
    preprocess_function,
    batched=True
)

tokenized_test = test_dataset.map(
    preprocess_function,
    batched=True
)

Map:   0%|          | 0/3739 [00:00<?, ? examples/s]

Map:   0%|          | 0/467 [00:00<?, ? examples/s]

Map:   0%|          | 0/468 [00:00<?, ? examples/s]

In [46]:
# =========================================================
# CEK HASIL TOKENISASI
# =========================================================

print("\nHASIL TOKENISASI:")
print(tokenized_train[0])

print("\nLABEL SAMPLE:")
print(tokenized_train[0]["labels"][:20])

HASIL TOKENISASI:
{'input': 'generate apa: Vina menemukan empat sudut gambar.', 'target': 'Apa yang Vina temukan?', '__index_level_0__': 2715, 'input_ids': [0, 20557, 877, 6256, 102, 35, 468, 1243, 604, 991, 1350, 260, 2841, 11632, 2628, 417, 1182, 34796, 271, 4, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'labels': [0, 250, 6709, 1423, 1097, 468, 1243, 11030, 1350, 260, 116, 2, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100]}

LABEL SAMPLE:
[0, 250, 6709, 1423, 1097, 468, 1243, 11030, 1350, 260, 116, 2, -100, -100, -100, -100, -100, -100, -100, -100]

In [ ]:
# =========================================================
# TRAINING ARGUMENT
# =========================================================

training_args = Seq2SeqTrainingArguments(

    output_dir="./indobart-qg",

    evaluation_strategy="epoch",

    save_strategy="epoch",

    learning_rate=3e-5,

    per_device_train_batch_size=8,

    per_device_eval_batch_size=8,

    num_train_epochs=5,

    predict_with_generate=True,

    logging_steps=10,

    fp16=torch.cuda.is_available(),

    load_best_model_at_end=True
)

In [48]:
# =========================================================
# TRAINER
# =========================================================

trainer = Seq2SeqTrainer(

    model=model,

    args=training_args,

    train_dataset=tokenized_train,

    eval_dataset=tokenized_valid,

    tokenizer=tokenizer
)

/usr/local/lib/python3.12/dist-packages/accelerate/accelerator.py:450: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = torch.cuda.amp.GradScaler(**kwargs)

In [49]:
# =========================================================
# TRAIN
# =========================================================

trainer.train()

Some non-default generation parameters are set in the model config. These should go into a GenerationConfig file (https://huggingface.co/docs/transformers/generation_strategies#save-a-custom-decoding-strategy-with-your-model) instead. This warning will be raised to an exception in v4.41.
Non-default generation parameters: {'early_stopping': True, 'num_beams': 4, 'no_repeat_ngram_size': 3, 'forced_bos_token_id': 0, 'forced_eos_token_id': 2}
Some non-default generation parameters are set in the model config. These should go into a GenerationConfig file (https://huggingface.co/docs/transformers/generation_strategies#save-a-custom-decoding-strategy-with-your-model) instead. This warning will be raised to an exception in v4.41.
Non-default generation parameters: {'early_stopping': True, 'num_beams': 4, 'no_repeat_ngram_size': 3, 'forced_bos_token_id': 0, 'forced_eos_token_id': 2}
Some non-default generation parameters are set in the model config. These should go into a GenerationConfig file (https://huggingface.co/docs/transformers/generation_strategies#save-a-custom-decoding-strategy-with-your-model) instead. This warning will be raised to an exception in v4.41.
Non-default generation parameters: {'early_stopping': True, 'num_beams': 4, 'no_repeat_ngram_size': 3, 'forced_bos_token_id': 0, 'forced_eos_token_id': 2}

Some non-default generation parameters are set in the model config. These should go into a GenerationConfig file (https://huggingface.co/docs/transformers/generation_strategies#save-a-custom-decoding-strategy-with-your-model) instead. This warning will be raised to an exception in v4.41.
Non-default generation parameters: {'early_stopping': True, 'num_beams': 4, 'no_repeat_ngram_size': 3, 'forced_bos_token_id': 0, 'forced_eos_token_id': 2}
Some non-default generation parameters are set in the model config. These should go into a GenerationConfig file (https://huggingface.co/docs/transformers/generation_strategies#save-a-custom-decoding-strategy-with-your-model) instead. This warning will be raised to an exception in v4.41.
Non-default generation parameters: {'early_stopping': True, 'num_beams': 4, 'no_repeat_ngram_size': 3, 'forced_bos_token_id': 0, 'forced_eos_token_id': 2}
Some non-default generation parameters are set in the model config. These should go into a GenerationConfig file (https://huggingface.co/docs/transformers/generation_strategies#save-a-custom-decoding-strategy-with-your-model) instead. This warning will be raised to an exception in v4.41.
Non-default generation parameters: {'early_stopping': True, 'num_beams': 4, 'no_repeat_ngram_size': 3, 'forced_bos_token_id': 0, 'forced_eos_token_id': 2}
Some non-default generation parameters are set in the model config. These should go into a GenerationConfig file (https://huggingface.co/docs/transformers/generation_strategies#save-a-custom-decoding-strategy-with-your-model) instead. This warning will be raised to an exception in v4.41.
Non-default generation parameters: {'early_stopping': True, 'num_beams': 4, 'no_repeat_ngram_size': 3, 'forced_bos_token_id': 0, 'forced_eos_token_id': 2}
Some non-default generation parameters are set in the model config. These should go into a GenerationConfig file (https://huggingface.co/docs/transformers/generation_strategies#save-a-custom-decoding-strategy-with-your-model) instead. This warning will be raised to an exception in v4.41.
Non-default generation parameters: {'early_stopping': True, 'num_beams': 4, 'no_repeat_ngram_size': 3, 'forced_bos_token_id': 0, 'forced_eos_token_id': 2}
Some non-default generation parameters are set in the model config. These should go into a GenerationConfig file (https://huggingface.co/docs/transformers/generation_strategies#save-a-custom-decoding-strategy-with-your-model) instead. This warning will be raised to an exception in v4.41.
Non-default generation parameters: {'early_stopping': True, 'num_beams': 4, 'no_repeat_ngram_size': 3, 'forced_bos_token_id': 0, 'forced_eos_token_id': 2}
Some non-default generation parameters are set in the model config. These should go into a GenerationConfig file (https://huggingface.co/docs/transformers/generation_strategies#save-a-custom-decoding-strategy-with-your-model) instead. This warning will be raised to an exception in v4.41.
Non-default generation parameters: {'early_stopping': True, 'num_beams': 4, 'no_repeat_ngram_size': 3, 'forced_bos_token_id': 0, 'forced_eos_token_id': 2}
There were missing keys in the checkpoint model loaded: ['model.encoder.embed_tokens.weight', 'model.decoder.embed_tokens.weight', 'lm_head.weight'].

TrainOutput(global_step=9350, training_loss=0.15757676068872692, metrics={'train_runtime': 1313.3525, 'train_samples_per_second': 28.469, 'train_steps_per_second': 7.119, 'total_flos': 2849755771699200.0, 'train_loss': 0.15757676068872692, 'epoch': 10.0})

In [50]:
# =========================================================
# SAVE MODEL
# =========================================================

trainer.save_model("model_indobart_qg")

tokenizer.save_pretrained(
    "model_indobart_qg"
)

print("\nMODEL BERHASIL DISIMPAN")

Some non-default generation parameters are set in the model config. These should go into a GenerationConfig file (https://huggingface.co/docs/transformers/generation_strategies#save-a-custom-decoding-strategy-with-your-model) instead. This warning will be raised to an exception in v4.41.
Non-default generation parameters: {'early_stopping': True, 'num_beams': 4, 'no_repeat_ngram_size': 3, 'forced_bos_token_id': 0, 'forced_eos_token_id': 2}

MODEL BERHASIL DISIMPAN

In [98]:
# =========================================================
# TEST GENERATE
# =========================================================

text = "mereka telah berhasil keluar"

input_text = (
    "generate Siapa: "
    + text
)

inputs = tokenizer(
    input_text,
    return_tensors="pt",
    truncation=True,
    max_length=128
)

device = model.device

inputs = {
    k: v.to(device)
    for k, v in inputs.items()
}

# =========================================================
# GENERATE
# =========================================================

output_ids = model.generate(

    **inputs,

    max_new_tokens=20,

    num_beams=5,

    no_repeat_ngram_size=3,

    repetition_penalty=3.0,

    length_penalty=1.2,

    early_stopping=True
)

# =========================================================
# DECODE
# =========================================================

hasil = tokenizer.decode(
    output_ids[0],
    skip_special_tokens=True,
    clean_up_tokenization_spaces=True
)

In [99]:
# =========================================================
# OUTPUT
# =========================================================

print("\n" + "=" * 50)
print("HASIL GENERATE")
print("=" * 50)

print("INPUT :")
print(text)

print("\nOUTPUT :")
print(hasil)

==================================================
HASIL GENERATE
==================================================
INPUT :
mereka telah berhasil keluar

OUTPUT :
Siapa yang berhasil keluar?

# TESTING MODEL

In [65]:
# =========================================================
# LOAD MODEL
# =========================================================

model_path = "model_indobart_qg"

tokenizer = AutoTokenizer.from_pretrained(
    model_path
)

model = AutoModelForSeq2SeqLM.from_pretrained(
    model_path
)

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

model.to(device)

print("Model loaded!")

Model loaded!

In [93]:
# =========================================================
# UPLOAD FILE TXT
# =========================================================

from google.colab import files

uploaded = files.upload()

file_name = list(uploaded.keys())[0]

Saving cerita_102.txt to cerita_102.txt

In [110]:
# =========================================================
# BACA FILE
# =========================================================

with open(file_name, "r", encoding="utf-8") as f:
    text = f.read()

print(text[:1000])

Pada zaman dahulu kala, tinggallah sebuah keluarga. Ayah, Ibu, serta tiga anak mereka. Suatu ketiga, sang Ayah meninggal dunia. Ia dimakamkan di pemakaman umum tepi kota yang cukup jauh. Pada hari ketujuh setelah sang Ayah wafat, Ibu ketiga anak itu masih merasa sedih kehilangan suaminya. Ia ingin membawa bunga ke makam suaminya. Maka ia berpesan pada ketiga anaknya. “Ibu akan pergi membawa bunga untuk di makam Ayah. Selama Ibu pergi, kalian harus saling menjaga, ya. Sebab ada raksasa tua yang jahat. Dia pandai menyamar menjadi manusia. Dia bisa meniru suara dan rupa. Kalian harus berhati-hati. Siapapun yang datang, jangan bukakan pintu.” Ketiga anak itu berjanji akan berhati-hati. Mereka mengantar ibu mereka sampai di muka rumah. “Adik-adik, ayo, cepat masuk rumah lagi,” kata si anak pertama pada kedua adiknya. Sang Ibu memerhatikan ketiga anaknya dari jauh dengan agak cemas. Namun ia ingin sekali membawa bunga untuk makam suaminya. Maka, ia pun pergi dengan hati gelisah. Baru saja sa

In [111]:
# =========================================================
# SPLIT KALIMAT
# =========================================================

kalimat_list = re.split(r'(?<=[.!?])\s+', text)

kalimat_list = [
    k.strip()
    for k in kalimat_list
    if len(k.strip()) > 3
]

print("\nJumlah kalimat:", len(kalimat_list))

Jumlah kalimat: 137

In [112]:
# =========================================================
# FUNCTION GENERATE
# =========================================================

def generate_question(text, tipe):

    input_text = f"generate {tipe}: {text}"

    inputs = tokenizer(
        input_text,
        return_tensors="pt",
        truncation=True,
        max_length=128
    )

    inputs = {
        k: v.to(device)
        for k, v in inputs.items()
    }

    output_ids = model.generate(

        **inputs,

        max_new_tokens=32,

        num_beams=5,

        no_repeat_ngram_size=3,

        repetition_penalty=3.0,

        length_penalty=1.2,

        early_stopping=True
    )

    hasil = tokenizer.decode(
        output_ids[0],
        skip_special_tokens=True,
        clean_up_tokenization_spaces=True
    )

    return hasil

In [113]:
def detect_relevant_types(text):

    text = text.lower()

    tipe = []

    # selalu bisa
    tipe.append("siapa")
    tipe.append("apa")

    # lokasi
    if " di " in f" {text} ":
        tipe.append("dimana")

    # tujuan
    if " ke " in f" {text} ":
        tipe.append("kemana")

    # asal
    if " dari " in f" {text} ":
        tipe.append("darimana")

    # waktu
    waktu_keywords = [
        "pagi",
        "siang",
        "malam",
        "sore",
        "kemarin",
        "besok",
        "hari ini",
        "minggu lalu",
        "tahun lalu",
        "bulan lalu",
        "hari ini",
        "senin",
        "selasa",
        "rabu",
        "kamis",
        "jumat",
        "sabtu",
        "minggu",
        "jam",
        "menit",
        "detik",
        "hari",
        "minggu",
        "tahun",
        "bulan",
        "detik",
        "menit",
        "pukul"
    ]

    if any(k in text for k in waktu_keywords):
        tipe.append("kapan")

    return tipe

In [114]:
# =========================================================
# TIPE PERTANYAAN
# =========================================================

tipe_list = [
    "siapa",
    "apa",
    "dimana",
    "kemana",
    "darimana",
    "kapan"
]

In [115]:
# =========================================================
# GENERATE SEMUA
# =========================================================

hasil = []

for kalimat in kalimat_list:

    print("\n")
    print("=" * 60)
    print("KALIMAT:")
    print(kalimat)

    relevant_types = detect_relevant_types(
    kalimat
    )

    for tipe in relevant_types:

        try:

            pertanyaan = generate_question(
                kalimat,
                tipe
            )

            hasil.append({

                "kalimat": kalimat,

                "tipe": tipe,

                "pertanyaan": pertanyaan
            })

            print(f"\n[{tipe.upper()}]")
            print(pertanyaan)

        except Exception as e:

            print(f"ERROR {tipe}: {e}")

============================================================
KALIMAT:
Pada zaman dahulu kala, tinggallah sebuah keluarga.

[SIAPA]
Siapa yang tinggallah sebuah keluarga dahulu kala,?

[APA]
Apa yang sebuah keluarga dahulu kala,?


============================================================
KALIMAT:
Ayah, Ibu, serta tiga anak mereka.

[SIAPA]
Siapa yang tiga anak mereka?

[APA]
Apa yang tiga anak mereka?


============================================================
KALIMAT:
Suatu ketiga, sang Ayah meninggal dunia.

[SIAPA]
Siapa yang meninggal dunia?

[APA]
Apa yang meninggal dunia?


============================================================
KALIMAT:
Ia dimakamkan di pemakaman umum tepi kota yang cukup jauh.

[SIAPA]
Siapa yang dimakamkan di pemakaman umum tepi kota yang cukup?

[APA]
Apa yang tepi kota yang cukup?

[DIMANA]
Di mana Ia dimakamkan?


============================================================
KALIMAT:
Pada hari ketujuh setelah sang Ayah wafat, Ibu ketiga anak itu masih merasa sedih kehilangan suaminya.

[SIAPA]
Siapa yang merasa pada hari?

[APA]
Apa yang Ibu ketujuh rasa pada hari?

[KAPAN]
Kapan  Ibu ketujuh?


============================================================
KALIMAT:
Ia ingin membawa bunga ke makam suaminya.

[SIAPA]
Siapa yang ingin membawa bunga ke makam suam nya?

[APA]
Apa yang Ia bawa ke makam suam nya?

[KEMANA]
Ke mana Ia ingin membawa bunga?


============================================================
KALIMAT:
Maka ia berpesan pada ketiga anaknya.

[SIAPA]
Siapa yang berpesan pada ketiga anak nya?

[APA]
Apa yang berpesan pada ketiga anak?


============================================================
KALIMAT:
“Ibu akan pergi membawa bunga untuk di makam Ayah.

[SIAPA]
Siapa yang akan pergi membawa bunga untuk di makam Ayah?

[APA]
Apa yang membawa bunga untuk di makam Ayah?

[DIMANA]
Di mana  membawa bunga?


============================================================
KALIMAT:
Selama Ibu pergi, kalian harus saling menjaga, ya.

[SIAPA]
Siapa yang pergi menjaga, ya?

[APA]
Apa yang pergi menjaga, ya?


============================================================
KALIMAT:
Sebab ada raksasa tua yang jahat.

[SIAPA]
Siapa yang raksasa?

[APA]
Apa yang jahat?


============================================================
KALIMAT:
Dia pandai menyamar menjadi manusia.

[SIAPA]
Siapa yang menyamar menjadi manusia?

[APA]
Apa yang menyamar menjadi?


============================================================
KALIMAT:
Dia bisa meniru suara dan rupa.

[SIAPA]
Siapa yang meniru suara dan rupa?

[APA]
Apa yang bisa tiru?


============================================================
KALIMAT:
Kalian harus berhati-hati.

[SIAPA]
Siapa yang berhati-hati?

[APA]
Apa yang berhati-hati?


============================================================
KALIMAT:
Siapapun yang datang, jangan bukakan pintu.” Ketiga anak itu berjanji akan berhati-hati.

[SIAPA]
Siapa yang datang akan pintu?

[APA]
Apa yang memjanji akan pintu?


============================================================
KALIMAT:
Mereka mengantar ibu mereka sampai di muka rumah.

[SIAPA]
Siapa yang mengantar ibu mereka sampai di muka rumah?

[APA]
Apa yang Mereka antar di muka rumah?

[DIMANA]
Di mana mereka mengantar ibu mereka?


============================================================
KALIMAT:
“Adik-adik, ayo, cepat masuk rumah lagi,” kata si anak pertama pada kedua adiknya.

[SIAPA]
Siapa yang cepat?

[APA]
Apa yang ayo, cepat?


============================================================
KALIMAT:
Sang Ibu memerhatikan ketiga anaknya dari jauh dengan agak cemas.

[SIAPA]
Siapa yang memerhatikan ketiga anak nya dengan agak cemas?

[APA]
Apa yang memerhatikan ketiga anak nya dengan agak cemas?

[DARIMANA]
Dari mana  memerhatikan ketiga anak nya?


============================================================
KALIMAT:
Namun ia ingin sekali membawa bunga untuk makam suaminya.

[SIAPA]
Siapa yang ingin membawa bunga untuk makam suam nya?

[APA]
Apa yang Namun ia bawa sekali?


============================================================
KALIMAT:
Maka, ia pun pergi dengan hati gelisah.

[SIAPA]
Siapa yang pergi dengan hati gelisah?

[APA]
Apa yang pergi dengan hati gelisah?


============================================================
KALIMAT:
Baru saja sang Ibu pergi, raksasa tua yang diceritakan sang Ibu tadi, datang ke rumah ketiga anak itu.

[SIAPA]
Siapa yang pergi raksasa sang Ibu tadi anak itu?

[APA]
Apa yang datang sang Ibu pergi ke rumah ketiga anak itu?

[KEMANA]
Ke mana  datang?


============================================================
KALIMAT:
Ia mengetuk pintu dan berkata, “Anak-anak, ibumu sudah kembali.” “Kalau kau ibu kami, tunjukkan tanganmu!” kata ketiga anak itu.

[SIAPA]
Siapa yang mengetuk pintu?

[APA]
Apa yang Ia kembali?


============================================================
KALIMAT:
Raksasa tua itu menuruti perintah mereka, dan menunjukan tangannya.

[SIAPA]
Siapa yang menuruti perintah mereka,?

[APA]
Apa yang menuruti perintah mereka,?


============================================================
KALIMAT:
Ketiga anak itu bergantian mengintip di lubang kecil di pintu.

[SIAPA]
Siapa yang bergantian mengintip di pintu?

[APA]
Apa yang bergantian mengintip di pintu?

[DIMANA]
Di mana Ketiga anak itu bergantian mengintip?


============================================================
KALIMAT:
Tampak sebuah tangan yang berbulu-bulu tebal dan kasar.

[SIAPA]
Siapa yang berbulu-bulu tebal?

[APA]
Apa yang berbulu-bulu tebal?


============================================================
KALIMAT:
“Tangan ibu kami kecil dan halus.

[SIAPA]
Siapa yang ibu kami kecil?

[APA]
Apa yang kami kecil?


============================================================
KALIMAT:
Tidak berbulu seperti itu.

[SIAPA]
Siapa yang berbulu seperti itu?

[APA]
Apa yang berbulu seperti itu?


============================================================
KALIMAT:
Kau pasti raksasa tua jahat,” kata anak-anak itu.

[SIAPA]
Siapa yang raksasa tua jahat?

[APA]
Apa yang raksasa?


============================================================
KALIMAT:
Raksasa tua itu segera pergi dari rumah itu.

[SIAPA]
Siapa yang pergi segera dari rumah itu?

[APA]
Apa yang pergi segera dari rumah itu?

[DARIMANA]
Dari mana Raksasa?


============================================================
KALIMAT:
Ia mencari alat cukur, lalu mencukur habis semua bulu-bulu di tangannya.

[SIAPA]
Siapa yang mencari alat cukur, lalu?

[APA]
Apa yang Ia cari di tangan nya?

[DIMANA]
Di mana  mencari alat cukur?


============================================================
KALIMAT:
Ia juga mengambil tepung gandum, dan menggosok ke tangannya.

[SIAPA]
Siapa yang mengambil tepung gandum, juga?

[APA]
Apa yang Ia ambil juga?

[KEMANA]
Ke mana  Ia?


============================================================
KALIMAT:
Lalu ia kembali ke rumah ketiga anak itu.

[SIAPA]
Siapa yang kembali ke rumah ketiga anak itu?

[APA]
Apa yang kembali ke rumah ketiga anak itu?

[KEMANA]
Ke mana  kembali?


============================================================
KALIMAT:
“Sekarang ibumu sudah kembali,” kata raksasa tua itu di depan pintu.

[SIAPA]
Siapa yang sudah kembali di depan pintu?

[APA]
Apa yang sudah kembali di depan pintu?

[DIMANA]
Di mana  sudah kembali?


============================================================
KALIMAT:
“Kalau kau ibu kami, tunjukkan tanganmu!” kata ketiga anak itu.

[SIAPA]
Siapa yang tunjukkan tanganmu?

[APA]
Apa yang kata ketiga anak itu?


============================================================
KALIMAT:
Raksasa itu pun menunjukan tangannya.

[SIAPA]
Siapa yang menunjukan tangan nya?

[APA]
Apa yang menunjukan tangan nya?


============================================================
KALIMAT:
Dari lubang kecil, ketiga anak itu mengintip.

[SIAPA]
Siapa yang mengintip ketiga anak itu?

[APA]
Apa yang Dari lubang kecil,?

[DARIMANA]
Dari mana ketiga anak itu?


============================================================
KALIMAT:
Mereka melihat tangan yang tidak berbulu dan berkulit putih.

[SIAPA]
Siapa yang melihat berbulu tidak?

[APA]
Apa yang Mereka lihat tidak?


============================================================
KALIMAT:
Persis seperti tangan ibu mereka.

[SIAPA]
Siapa yang seperti tangan ibu mereka?

[APA]
Apa yang mereka seperti?


============================================================
KALIMAT:
Namun, napas raksasa jahat itu sangat bau.

[SIAPA]
Siapa yang raksasa jahat itu?

[APA]
Apa yang raksasa?


============================================================
KALIMAT:
Suaranya pun sangat besar seperti suara beruang.

[SIAPA]
Siapa yang suara beruang sangat besar?

[APA]
Apa yang suara beruang sangat?


============================================================
KALIMAT:
“Suara ibu kami lebih halus daripada suaramu,” kata anak-anak itu.Raksasa jahat itu lalu pergi.

[SIAPA]
Siapa yang pergi?

[APA]
Apa yang kami lebih halus daripada suaramu?


============================================================
KALIMAT:
Ia meminum air rendaman bunga mawar, lalu kembali ke rumah anak-anak itu untuk ketiga kalinya.

[SIAPA]
Siapa yang meminum air rendaman bunga mawar ke rumah anak-anak itu?

[APA]
Apa yang Ia pinum ke rumah anak-anak itu?

[KEMANA]
Ke mana Ia meminum ketiga kal nya?


============================================================
KALIMAT:
“Ibumu sudah kembali!

[SIAPA]
Siapa yang sudah kembali?

[APA]
Apa yang sudah kembali?


============================================================
KALIMAT:
Maafkan Ibu, ya, karena terlambat pulang ke rumah,” kata raksasa itu dengan nada lembut.

[SIAPA]
Siapa yang terlambat pulang ke rumah,?

[APA]
Apa yang terlambat ke rumah,” kata raksasa itu?

[KEMANA]
Ke mana  terlambat pulang?


============================================================
KALIMAT:
Mendengar suara yang lembut dan aroma mawar seharum ibu mereka, ketiga anak itu sangat gembira.

[SIAPA]
Siapa yang lembut?

[APA]
Apa yang suara yang lembut?


============================================================
KALIMAT:
“Oh, Ibu sudah datang!” ketiga anak itu buru-buru membuka pintu.

[SIAPA]
Siapa yang sudah datang?

[APA]
Apa yang Ibu datang?


============================================================
KALIMAT:
Dalam sekejap, raksasa itu merubah wujudnya menjadi seperti ibu mereka.

[SIAPA]
Siapa yang menjap, raksasa itu?

[APA]
Apa yang menjap, raksasa itu?


============================================================
KALIMAT:
Ketiga anak itu membiarkan ibu palsu itu masuk.

[SIAPA]
Siapa yang membiarkan ibu palsu itu?

[APA]
Apa yang membiarkan ibu palsu itu?


============================================================
KALIMAT:
Raksasa itu lalu berkata,  “Anak-anak, sebaiknya kalian tidur sekarang.

[SIAPA]
Siapa yang berkata, sebaik nya?

[APA]
Apa yang berkata, sebaik nya?


============================================================
KALIMAT:
Hari sudah malam.”

Seperti biasa, anak pertama dan anak kedua tidur di satu kamar.

[SIAPA]
Siapa yang sudah malam di satu kamar?

[APA]
Apa yang sudah malam di satu kamar?

[DIMANA]
Di mana  sudah malam?

[KAPAN]
Kapan  sudah malam?


============================================================
KALIMAT:
Sementara anak bungsu tidur bersama ibu mereka.

[SIAPA]
Siapa yang bungsu tidur bersama ibu mereka?

[APA]
Apa yang bungsu tidur bersama ibu mereka?


============================================================
KALIMAT:
Jadi, kali itu, si anak bungsu tidur bersama raksasa tua yang kini tampak seperti ibu mereka.

[SIAPA]
Siapa yang tampak seperti ibu mereka?

[APA]
Apa yang seperti ibu mereka?


============================================================
KALIMAT:
Di tengah malam yang sunyi, tiba-tiba terdengar bunyi gemerisik dari arah dapur.

[SIAPA]
Siapa yang terdengar bunyi gemerisik dari arah dapur?

[APA]
Apa yang terdengar bunyi dapur?

[DIMANA]
Di mana  terdengar?

[DARIMANA]
Dari mana  terdengar?

[KAPAN]
Kapan  terdengar?


============================================================
KALIMAT:
Anak pertama dan kedua terbangun.

[SIAPA]
Siapa yang terbangun?

[APA]
Apa yang terbangun?


============================================================
KALIMAT:
Mereka menajamkan telinga dan samar-samar mendengar bunyi besi beradu.

[SIAPA]
Siapa yang menajamkan telinga dan samar-samar?

[APA]
Apa yang Mereka majamkan?

[KAPAN]
Kapan Mereka menajamkan telinga?


============================================================
KALIMAT:
Dengan ketakutan, mereka berdua mengendap keluar dari kamar, dan mengintip ke dapur.

[SIAPA]
Siapa yang mengendap keluar dari kamar,?

[APA]
Apa yang mereka berdua ke dapur?

[KEMANA]
Ke mana mereka berdua?

[DARIMANA]
Dari mana mereka berdua?


============================================================
KALIMAT:
Dari balik pintu dapur, mereka melihat sosok punggung ibu mereka.

[SIAPA]
Siapa yang melihat sosok punggung ibu mereka?

[APA]
Apa yang mereka lihat?

[DARIMANA]
Dari balik pintu dapur?


============================================================
KALIMAT:
Ia sedang menyiapkan bahan makanan.

[SIAPA]
Siapa yang menyiapkan bahan makanan?

[APA]
Apa yang Ia siapkan sedang?


============================================================
KALIMAT:
Ia memotong-motong sayur, menghancurkan rempah-rempah, lalu memasukkannya ke dalam air mendidih.

[SIAPA]
Siapa yang memotong-motong sayur ke dalam air?

[APA]
Apa yang Ia potongkan ke dalam air mendidih?

[KEMANA]
Ke mana Ia memotong-motong sayur?


============================================================
KALIMAT:
Sang Ibu lalu mengambil pisau daging, lalu mengasahnya dengan menggesekkan dengan pisau lain.

[SIAPA]
Siapa yang mengambil pisau daging, lalu?

[APA]
Apa yang mengambil pisau daging, lalu?


============================================================
KALIMAT:
Ternyata, bunyi itulah yang mereka dengar dari kamar.

[SIAPA]
Siapa yang dengar dari kamar?

[APA]
Apa yang mereka dengar dari kamar?

[DARIMANA]
Dari mana  Ternyata?


============================================================
KALIMAT:
“Ibu, apa yang Ibu lakukan?” tanya anak pertama penasaran.

[SIAPA]
Siapa yang lakukan?

[APA]
Apa yang  lakukan?


============================================================
KALIMAT:
“Ooh, ehm, Ibu sedang menyiapkan sarapan pagi untuk kalian, Sayang,” kata sang ibu palsu tanpa membalik tubuhnya.

[SIAPA]
Siapa yang membalik sarapan pagi untuk kalian, sayang?

[APA]
Apa yang Ibu siapkan?

[KAPAN]
Kapan  membalik sarapan?


============================================================
KALIMAT:
“Tapi, ini masih malam, Bu,” ujar anak kedua heran.

[SIAPA]
Siapa yang masih malam, Bu,?

[APA]
Apa yang masih malam, Bu,?

[KAPAN]
Kapan  masih malam?


============================================================
KALIMAT:
“Oh, sebenarnya, Ibu sangat kelaparan.

[SIAPA]
Siapa yang Ibu warnya sangat kelaparan?

[APA]
Apa yang Ibu warnya?


============================================================
KALIMAT:
Ibu baru pulang dari perjalanan yang sangat jauh, kan?” kata sang ibu palsu sambil terus mengasah pisau daging.

[SIAPA]
Siapa yang pulang terus?

[APA]
Apa yang mengasah pisau daging?

[DARIMANA]
Dari mana  Ibu?


============================================================
KALIMAT:
“Apa yang sedang Ibu masak?”  kata pertama sambil berjalan mendekat, ingin melihat apa yang ada di depan ibu mereka.

[SIAPA]
Siapa yang sedang Ibu?

[APA]
Apa yang sedang Ibu?

[DIMANA]
Di mana  berjalan?


============================================================
KALIMAT:
Namun, sang ibu berusaha menutupi benda yang ada di depannya.

[SIAPA]
Siapa yang berusaha menutupi benda yang ada?

[APA]
Apa yang berusaha menutupi benda yang ada sang ibu?

[DIMANA]
Di mana Namun berusaha?


============================================================
KALIMAT:
Anak kedua ikut mendekat juga dari arah lain.

[SIAPA]
Siapa yang ikut mendekat juga dari arah lain?

[APA]
Apa yang Anak kedua ikut dari arah lain?

[DARIMANA]
Dari mana Anak kedua ikut mendekat?


============================================================
KALIMAT:
Sang ibu palsu kembali bergerak ke samping, agar anak kedua tidak bisa melihat.

[SIAPA]
Siapa yang bergerak kembali ke samping, agar anak kedua tidak?

[APA]
Apa yang bisa lihat kembali ke samping, agar anak?

[KEMANA]
Ke mana  bergerak?


============================================================
KALIMAT:
Namun, anak pertama jadi bisa melihat apa yang ada di depan si ibu palsu.

[SIAPA]
Siapa yang melihat apa yang ada pertama?

[APA]
Apa yang jadi bisa?

[DIMANA]
Di mana anak pertama jadi bisa?


============================================================
KALIMAT:
Ia sangat terkejut dan berseru,

 “Apa yang Ibu lakukan pada adik kami?!” Anak pertama terbelalak melihat adik bungsunya sedang berbaring di atas meja dapur dalam keadaan terikat.

[SIAPA]
Siapa yang melihat adik kami?!

[APA]
Apa yang terkejut dan berseru?

[DIMANA]
Di mana  terkejut?


============================================================
KALIMAT:
“Diam!” bentak si ibu palsu sambil menggebrak meja dengan suara berubah menggelegar.

[SIAPA]
Siapa yang berubah menggelegar?

[APA]
Apa yang suara gerar?


============================================================
KALIMAT:
Bulu-bulu kasar di tangannya lalu mulai tumbuh lagi.

[SIAPA]
Siapa yang tumbuh lagi di tangan nya?

[APA]
Apa yang mulai lagi di tangan nya?

[DIMANA]
Di mana  mulai tumbuh?


============================================================
KALIMAT:
Ketika si ibu palsu membalik tubuhnya, menengok ke arah kedua anak itu, matanya tampak merah berkilat.

[SIAPA]
Siapa yang membalik tubuh nya ke arah kedua anak itu?

[APA]
Apa yang membalik tubuh nya ke arah kedua anak itu?

[KEMANA]
Ke mana Ketika si ibu palsu membalik tubuh nya?


============================================================
KALIMAT:
Kulitnya berubah menjadi merah, dan dari hidungnya keluar asap.

[SIAPA]
Siapa yang berubah menjadi merah?

[APA]
Apa yang berubah menjadi merah keluar asap?

[DARIMANA]
Dari mana Kulit nya berubah menjadi merah?


============================================================
KALIMAT:
Tubuhnya berubah menjadi raksasa tua jahat lagi.

[SIAPA]
Siapa yang berubah menjadi raksasa?

[APA]
Apa yang berubah menjadi raksasa?


============================================================
KALIMAT:
Raksasa itu berbalik lalu mengulurkan tangannya untuk menangkap kedua anak itu.

[SIAPA]
Siapa yang Raksasa itu balurkan?

[APA]
Apa yang Raksasa itu balurkan?


============================================================
KALIMAT:
Dengan cepat mereka mundur ke arah dinding.

[SIAPA]
Siapa yang mundur ke arah dinding?

[APA]
Apa yang mereka mundur ke arah dinding?

[KEMANA]
Ke mana mereka mundur?


============================================================
KALIMAT:
Ketika raksasa itu menerjang hendak menangkap mereka, kembali mereka berkelit ke samping, sehingga kepala raksasa itu menabrak dinding rumah.

[SIAPA]
Siapa yang menabrak dinding rumah?

[APA]
Apa yang menabrak dinding rumah?

[KEMANA]
Ke mana Ketika raksasa itu menerjang?


============================================================
KALIMAT:
Dinding rumah pun hancur berlubang.

[SIAPA]
Siapa yang Dinding rumah pun hancur?

[APA]
Apa yang berlubang?


============================================================
KALIMAT:
Sementara, kepala raksasa itu terjebak di lubang dinding itu.

[SIAPA]
Siapa yang terjebak sementara, di lubang dinding itu?

[APA]
Apa yang terjebak di lubang dinding itu?

[DIMANA]
Di mana  terjebak?


============================================================
KALIMAT:
Dengan marah, raksasa itu meronta dan mengamuk.

[SIAPA]
Siapa yang meronta?

[APA]
Apa yang raksasa itu?


============================================================
KALIMAT:
Ia mencoba menarik kepalanya, namun tidak berhasil.

[SIAPA]
Siapa yang mencoba menarik kepal nya?

[APA]
Apa yang Ia cari mencoba?



In [109]:
# =========================================================
# DATAFRAME
# =========================================================

df_hasil = pd.DataFrame(hasil)

print("\n")
print(df_hasil.head(12))

ValueError: DataFrame constructor not properly called!

In [ ]:
# =========================================================
# SIMPAN CSV
# =========================================================

df_hasil.to_csv(
    "machine learning.csv",
    index=False,
    encoding="utf-8-sig"
)

print("\nCSV berhasil disimpan!")

#  EVALUASI BLEU SCORE

In [100]:
!pip install nltk evaluate -q

In [101]:
import pandas as pd

from nltk.translate.bleu_score import (
    sentence_bleu,
    SmoothingFunction
)

In [103]:
test_df = pd.read_csv("H6_test_dataset.csv")

In [104]:
hasil_bleu = []

for i in range(len(test_df)):

    input_text = test_df.iloc[i]["input"]

    reference = test_df.iloc[i]["target"]

    # tokenize input
    inputs = tokenizer(
        input_text,
        return_tensors="pt",
        truncation=True,
        max_length=128
    )

    # pindah ke GPU
    inputs = {
        k: v.to(model.device)
        for k, v in inputs.items()
    }

    # generate
    output_ids = model.generate(

        **inputs,

        max_new_tokens=20,

        num_beams=5,

        no_repeat_ngram_size=3,

        repetition_penalty=3.0,

        early_stopping=True
    )

    # decode
    prediction = tokenizer.decode(
        output_ids[0],
        skip_special_tokens=True
    )

    hasil_bleu.append({
        "input": input_text,
        "reference": reference,
        "prediction": prediction
    })

print("Selesai generate")

Selesai generate

In [105]:
df_bleu = pd.DataFrame(hasil_bleu)

df_bleu.head()

,input,reference,prediction
0,generate apa: Doni mengantarkan singkong rebus...,Apa yang Doni antarkan ke pos ronda?,Apa yang Doni antarkan ke pos ronda?
1,generate kemana: Mereka membawa barang belanja...,Ke mana Mereka membawa barang belanjaan?,Ke mana Mereka membawa barang belanjaan?
2,generate siapa: Andi mengucapkan terima kasih ...,Siapa yang mengucapkan terima kasih kepada ayah?,Siapa yang Andi ucapkan kepada ayah?
3,generate dimana: Adik bermain bola di halaman ...,Di mana Adik bermain bola?,Di mana Adik bermain bola?
4,generate siapa: Banyak penonton duduk di kursi...,Siapa yang duduk di kursi melingkar?,Siapa yang duduk di kursi melingkar?

In [106]:
smooth = SmoothingFunction().method1

bleu1_scores = []
bleu2_scores = []
bleu4_scores = []

for i in range(len(df_bleu)):

    reference = [
        df_bleu.iloc[i]["reference"].split()
    ]

    candidate = (
        df_bleu.iloc[i]["prediction"].split()
    )

    # BLEU-1
    bleu1 = sentence_bleu(
        reference,
        candidate,
        weights=(1, 0, 0, 0),
        smoothing_function=smooth
    )

    # BLEU-2
    bleu2 = sentence_bleu(
        reference,
        candidate,
        weights=(0.5, 0.5, 0, 0),
        smoothing_function=smooth
    )

    # BLEU-4
    bleu4 = sentence_bleu(
        reference,
        candidate,
        weights=(0.25, 0.25, 0.25, 0.25),
        smoothing_function=smooth
    )

    bleu1_scores.append(bleu1)
    bleu2_scores.append(bleu2)
    bleu4_scores.append(bleu4)

In [107]:
avg_bleu1 = sum(bleu1_scores) / len(bleu1_scores)
avg_bleu2 = sum(bleu2_scores) / len(bleu2_scores)
avg_bleu4 = sum(bleu4_scores) / len(bleu4_scores)

print("=" * 50)
print("HASIL BLEU SCORE")
print("=" * 50)

print(f"BLEU-1 : {avg_bleu1:.4f}")
print(f"BLEU-2 : {avg_bleu2:.4f}")
print(f"BLEU-4 : {avg_bleu4:.4f}")

==================================================
HASIL BLEU SCORE
==================================================
BLEU-1 : 0.7610
BLEU-2 : 0.7241
BLEU-4 : 0.6127

In [108]:
df_bleu["BLEU-1"] = bleu1_scores
df_bleu["BLEU-2"] = bleu2_scores
df_bleu["BLEU-4"] = bleu4_scores

df_bleu.to_csv(
    "7hasil_bleu_ML.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Hasil BLEU disimpan")

Hasil BLEU disimpan